factura:
    resource: "@FacturaBundle/Resources/config/routing.yml"
    prefix:   /

theme:
    resource: "@TemaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
