factura_index:
    path:     /
    defaults: { _controller: "FacturaBundle:Factura:index" }
    methods:  GET

factura_show:
    path:     /{idfactura}/show
    defaults: { _controller: "FacturaBundle:Factura:show" }
    methods:  GET

factura_new:
    path:     /new
    defaults: { _controller: "FacturaBundle:Factura:new" }
    methods:  [GET, POST]

factura_edit:
    path:     /{idfactura}/edit
    defaults: { _controller: "FacturaBundle:Factura:edit" }
    methods:  [GET, POST]

factura_delete:
    path:     /{idfactura}/delete
    defaults: { _controller: "FacturaBundle:Factura:delete" }
    methods:  DELETE

factura_reporte_index:
    path:     /reportes
    defaults: { _controller: "FacturaBundle:Reportes:index" }
    methods:  GET

factura_get_date:
    path:     /reportes/factura
    defaults: { _controller: "FacutraBundle:Reportes:getFactura" }
    methods:  POST